[project]
name = "csfd"
version = "0.1.0"
description = "Scrapes top 300 movies from CSFD.cz"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "beautifulsoup4>=4.13.4",
    "django>=5.2.4",
    "lxml>=6.0.0",
    "requests>=2.32.4",
]
