# Generated by Django 5.2.4 on 2025-07-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "url",
                    models.CharField(max_length=100, unique=True, verbose_name="url"),
                ),
            ],
            options={
                "verbose_name": "creator",
                "verbose_name_plural": "creators",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "url",
                    models.CharField(max_length=100, unique=True, verbose_name="url"),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(verbose_name="release year"),
                ),
                ("genre", models.CharField(max_length=100, verbose_name="genre")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="rating"
                    ),
                ),
                (
                    "poster",
                    models.CharField(
                        default="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
                        max_length=200,
                        verbose_name="poster",
                    ),
                ),
            ],
            options={
                "verbose_name": "movie",
                "verbose_name_plural": "movies",
                "ordering": ["-rating", "-release_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="MovieCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIRECTOR", "Director"),
                            ("AUTHOR", "Author"),
                            ("WRITER", "Writer"),
                            ("CINEMATOGRAPHY", "Cinematography"),
                            ("MUSIC", "Music"),
                            ("ACTOR", "Actor"),
                            ("PRODUCER", "Producer"),
                            ("EDITOR", "Editor"),
                            ("COSTUME_DESIGN", "Costume Design"),
                        ],
                        default="ACTOR",
                        max_length=15,
                        verbose_name="role",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_creators",
                        to="movies.creator",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_creators",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "movie creator",
                "verbose_name_plural": "movie creators",
                "ordering": ["movie__title", "creator__name"],
                "unique_together": {("movie", "creator", "role")},
            },
        ),
        migrations.AddField(
            model_name="creator",
            name="movies",
            field=models.ManyToManyField(
                related_name="creators",
                through="movies.MovieCreator",
                to="movies.movie",
            ),
        ),
    ]
